### ISSUE TITLE
Configure environments for publishing

### ISSUE THREAD

**Issue by potiuk** [apache/airflow-publish#10]
We need to have [environments](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment) configured as this is recommended best practice, becuse we should only have a handful of people (release manager) capable of publishig the releases, and this environment should be very separate and allow to only execute publishing workflows.

This however requires changes to [.asf.yaml](https://github.com/apache/infrastructure-asfyaml) as we should be able to configure such environments via .asf.yaml file. 

Currently .asf.yaml does not have the capability of configuring environments, but it should be rather straightforward to contribute changes to the .asf.yaml [processing python script ](https://github.com/apache/infrastructure-p6/blob/production/modules/gitbox/files/asfgit/package/asfyaml.py) to include it, because there is [API available](https://docs.github.com/en/rest/deployments/environments?apiVersion=2022-11-28) to manage the environments and we should be able to contribute it rather easily.

I already contributed once there https://github.com/apache/infrastructure-p6/commit/21b98e56ef7cd9c62fa20ec5b6aef008fb342971 - and we can again contribute back to the ASF and make it possible for all projects to configure environments.

**Comment by potiuk** [comment]
cc: @gopidesupavan -> maybe you would like to take a look at that - that would be a nice contribution not only for the Apache Airflow but eventually for the whole Apache Software Foundation and infrastructure of it.

**Comment by potiuk** [comment]
BTW. @gopidesupavan -> do you have account on the ASF JIRA (https://issues.apache.org/j) ? We will need to interact with Infra in the course of this project, so you will need one :)

**Comment by gopidesupavan** [comment]
> cc: @gopidesupavan -> maybe you would like to take a look at that - that would be a nice contribution not only for the Apache Airflow but eventually for the whole Apache Software Foundation and infrastructure of it.

Yeah will have a look :) thanks for sharing the references

**Comment by gopidesupavan** [comment]
> BTW. @gopidesupavan -> do you have account on the ASF JIRA (https://issues.apache.org/j) ? We will need to interact with Infra in the course of this project, so you will need one :)

Sure wi

> https://issues.apache.org/j

Just checked yeah i have access to jira :)

**Comment by potiuk** [comment]
What Account id ? - we have that issue in INFRA where we discuss it so I can add you to it https://issues.apache.org/jira/browse/INFRA-24678

**Comment by gopidesupavan** [comment]
> What Account id ? - we have that issue in INFRA where we discuss it so I can add you to it https://issues.apache.org/jira/browse/INFRA-24678

gopidesu

**Comment by gopidesupavan** [comment]
Got understand of code base to update asf yml. i am thinking of this yml structure WDYT? :) 

```
  environments:
    test-pypi:
      required_reviewers:
        - reviewer1
        - reviewer2
      prevent_self_review: true
      wait_timer: 1
      deployment_branch_policy:
        protected_branches: true
        custom_branch_policies: false

    pypi:
      required_reviewers:
        - reviewer1
        - reviewer2
      prevent_self_review: true
      wait_timer: 1
      deployment_branch_policy:
        protected_branches: false
        custom_branch_policies: true
        policies:
          - name: main
            type: branch
          - name: 1.0.0
            type: tag
          - name: "release/*/*"
```

Policies is required to create only when choose `custom_branch_policies` so basically , each deployment environment can have multiple custom policies or choose `protected_branches`

not sure which root element is better `environments:` or `deployment_environments: ` :) ?
